try for a failure

diff --git a/.github/workflows/ci-frontend-a11y.yml b/.github/workflows/ci-frontend-a11y.yml
--- a/.github/workflows/ci-frontend-a11y.yml
+++ b/.github/workflows/ci-frontend-a11y.yml
@@ -60,5 +60,6 @@ jobs:
 
       - name: Run pa11y-ci
         run: |
-            npm run test:pa11y
-            echo "pa11y-ci tests finished."
+          set -e # Ensure the script fails if any command fails
+          npm run test:pa11y
+          echo "pa11y-ci tests finished."
